services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lead_auto
    volumes:
      - lead_auto_postgres:/var/lib/postgresql/data

volumes:
  lead_auto_postgres:
